---

name: Fetch Docker image
on:
  workflow_dispatch:
    inputs:
      imageName:
        description: 'Image to fetch'
        required: true
      tag:
        description: 'Tag'
        default: 'latest'
        required: true

jobs:
  FetchingOnTarget:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Image
      run: |
        docker pull ${{ github.event.inputs.imageName }}:${{ github.event.inputs.tag }}
    
    - name: Save Image
      run: |
        echo "GITHUB_IMAGE_SHORT=${${{ github.event.inputs.imageName }}##*/}" >> $GITHUB_ENV
        echo $GITHUB_ENV
        echo ${{ env }}
        docker save ${{ github.event.inputs.imageName }}:${{ github.event.inputs.tag }} | gzip > ${{ env.GITHUB_IMAGE_SHORT }}.tar.gz

        
    - name: Upload Archive
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ env.GITHUB_IMAGE_SHORT }}
        path: ./
        retention-days: 2
