---

name: Fetch Docker image
on:
  workflow_dispatch:
    inputs:
      imageName:
        description: 'Image to fetch'
        required: true
      tag:
        description: 'Tag'
        default: 'latest'
        required: true
      short:
        description: 'Short name'
        required: true

jobs:
  FetchingOnTarget:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Image
      run: |
        curl -X GET https://${{ github.event.inputs.imageName }}:5000/v2/_catalog || true
        docker pull ${{ github.event.inputs.imageName }}:${{ github.event.inputs.tag }}
    
    - name: Save Image
      run: |
        #echo "GITHUB_IMAGE_SHORT=${${{ github.event.inputs.imageName }}##*/}" >> $GITHUB_ENV
        docker save ${{ github.event.inputs.imageName }}:${{ github.event.inputs.tag }} | gzip > ${{ github.event.inputs.short }}.tar.gz

        
    - name: Upload Archive
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ github.event.inputs.short }}
        path: ./
        retention-days: 2
