---

name: Fetch Helm Chart
on:
  workflow_dispatch:
    inputs:
      chartRepo:
        description: 'Repository'
        default: 'https://charts.bitnami.com/bitnami'
        required: true
      chartName:
        description: 'Chart to fetch'
        required: true
      tag:
        description: 'Tag'
        required: false

jobs:
  FetchingOnTarget:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-helm@v3
      # with:
      #   version: '<version>' # default is latest (stable)
      #   token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
      id: install

    - name: Add Repo
      run: |
        helm repo add myrepo ${{ github.event.inputs.chartRepo }}
        helm repo update

    - name: Fetch Chart
      run: |
        mkdir chart
        [[ ! -z ${{ github.event.inputs.tag }} ]] && tag=echo ":${{ github.event.inputs.tag }}"
        helm pull myrepo/${{ github.event.inputs.chartName }}$tag --untar --untardir ./chart
    
    - name: Upload Archive
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ github.event.inputs.chartName }}
        path: ./chart
        retention-days: 2

